### ISSUE TITLE
Support for 0.10.0 message format

### ISSUE THREAD

**Issue by MartinNowak** [zendesk/ruby-kafka#199]
Since 0.10.0 message might include a timestamp field.
http://kafka.apache.org/documentation.html#upgrade_10
http://kafka.apache.org/documentation.html#upgrade_10_breaking

**Comment by dasch** [comment]
Since there's no good way to detect which version of Kafka a cluster is running I'd like to keep this library 0.9 only for the time being. At some point we'll switch everything over to 0.10, but I'd like to avoid having to support multiple versions. After 0.10 things will be different due to the API version discovery mechanism that was added.

**Comment by leifg** [comment]
What about having a version attribute in the client that defaults to 0.9.0 that way 0.10.0 features can be used without breaking backwards compatibility.

**Comment by dasch** [comment]
That would still require maintenance of the different request/response serialization formats. Since I don't feel any of the 0.10 features warrant that extra work I'm going to push support for 0.10 features to a later time.

**Comment by dasch** [comment]
@MartinNowak I've just released `v0.5.0.beta1` with support for Kafka 0.10. Would you be willing to run this in production for some time and see if everything works as expected?

**Comment by MartinNowak** [comment]
Yes. should have some time next week to cater for Kafka and ruby-kafka updates.

**Comment by dasch** [comment]
@MartinNowak I've since pulled that release from Rubygems because I didn't feel that I wazs able to adequately support it without running Kafka 0.10 myself. I hope to re-release soon-ish.
