### ISSUE TITLE
Implement the Consumer API

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#20]
In Kafka, consumers form consumer groups around topics, dividing the responsibility for consuming individual topic partitions among themselves. Furthermore, a consumer can subscribe to multiple topics, thus participating in several groups at once. This is useful for e.g. joining two topics.

We need to figure out what level of abstraction to provide to users of ruby-kafka. Since processing frameworks can be built on top of the library, flexibility is important. At the same time, it should be possible to just use this library, so simplicity is also desirable.

The Java API is based on the consumer _subscribing_ to one or more topics, and then _polling_ for new messages:

```java
KafkaConsumer<String, String> consumer = new KafkaConsumer<String, String>(props);
consumer.subscribe(Arrays.asList("foo", "bar"));
while (true) {
    ConsumerRecords<String, String> records = consumer.poll(100);
    for (ConsumerRecord<String, String> record : records)
        System.out.printf("offset = %d, key = %s, value = %s", record.offset(), record.key(), record.value());
}
```

The most low-level Ruby API could look like this:

```ruby
consumer = kafka.get_consumer
consumer.subcribe("ad-impressions", "ad-clicks")

loop do
  messages = consumer.poll
  messages.each do |message|
    puts message.topic, message.partition, message.offset, message.key, message.value
  end
  consumer.commit_offsets
end
```

This would mix messages from all topics that a consumer subscribes to. Higher level consumer loops can then be added to e.g. direct messages to topic-specific handlers. Another option is to instead return a list of message batches, with each batch being specific to a topic partition:

```ruby
batches = consumer.poll
batches.each do |batch|
  puts batch.topic, batch.partition, batch.highwater_mark_offset

  batch.messages.each do |message|
    puts message.offset, message.key, message.value
  end

  batch.commit_offset
end
```

One important issue to consider is offset commits. In the above examples, we either commit *all* offsets for a consumer or, in the second example, individually commit offsets for specific partitions.

I want ruby-kafka to align itself with the protocol so that we can achieve maximum performance, hopefully without the API being too weird. The protocol specifically allows offset commits to include the offsets for several topic partitions at a time, so if we intend to minimize the number of round trips to the brokers, we should commit offsets in bulk (the first example.) That does, however, provide less granular control. I think allowing both would be preferable.

Furthermore, we can provide a high-level message loop that automatically commits offsets after each batch has been processed:

```ruby
consumer.each_message do |message|
  puts message.topic, message.partition, message.offset, message.key, message.value
end
```

###### Tasks

- [x] Implement high level message oriented API.
- [x] Implement low level batch oriented API.

**Comment by mensfeld** [comment]
- I think that consumer should be dedicated to a single topic - responsibility of joining topics should be handled by user logic since it can be implemented there. Is there a reason for a single consumer to consume many topics? How would that work if one of the topics would be heavily loaded and second almost not at all? It also sounds like a complicated logic behind which there might hide many errors.

About committing offsets: Ruby is shitty with multithreading so there should be a way to do both. Of course that performance will drop down but on the other hand lets say I listen to 10 topics on 10 consumers and I commit offsets all together and then I shutdown my code in the middle of data processing. Now with poseidon I can commit the current offset state ASAP for each topic, so un next code run I will start from when I've ended. How would that work if I would have a buffer in which I have a number and then on shutdown I have to change value that is already in the buffer?

What I believe is required from consumer:

- Autodiscovery of Kafka cluster structure based on Zookeeper - that way there would not be need to restart consumer on each cluster change. it should automatically reconfigure. Now we do that on our own: https://github.com/karafka/karafka/blob/master/lib/karafka/connection/broker_manager.rb but for me it is a really low level feature. The upper layer can be implemented in users code - for example let's say that we shut down all the current Kafkas and spin up new once (one by one it the same cluster) - at some point currently running process won't have Kafkas to listen to. With autodiscovery I could just recreate a consumer and it would fetch new brokers. That would require from me catching a single error and having a failover loop.

**Comment by dasch** [comment]
> - I think that consumer should be dedicated to a single topic - responsibility of joining topics should be handled by user logic since it can be implemented there. Is there a reason for a single consumer to consume many topics? How would that work if one of the topics would be heavily loaded and second almost not at all? It also sounds like a complicated logic behind which there might hide many errors.

That's based on how the Kafka protocol works: consumers form groups around a set of topics, not necessarily just one. This makes sense if a consumer needs to merge two topics, e.g. ad impressions and clicks. While it *would* be possible to restrict a consumer to a single topic, that would impede flexibility and is the responsibility of a higher-level API, in my opinion. This mirrors my implementation of Producer, which buffers and sends messages for an arbitrary number of topics.

> About committing offsets: Ruby is shitty with multithreading so there should be a way to do both. Of course that performance will drop down but on the other hand lets say I listen to 10 topics on 10 consumers and I commit offsets all together and then I shutdown my code in the middle of data processing. Now with poseidon I can commit the current offset state ASAP for each topic, so un next code run I will start from when I've ended. How would that work if I would have a buffer in which I have a number and then on shutdown I have to change value that is already in the buffer?

I'm not quite sure what you mean with "buffer" here. My idea is that a consumer keeps track of the "consumed" offset for each topic/partition it's subscribed to, which would be the offset of the last message in each partition batch, as well as the "processed" offset for each topic/partition. After processing a message, the "processed" offset for its topic partition will be set to the offset of the message, or, if the low level API is used, the commit call on the message batch will set the "processed" offset to be the offset of the last message in the batch. When calling commit on the consumer itself, the "processed" offset would simply be set to be the "consumed" offset.

Actually committing the offsets would then be a separate logical action, where the consumer would commit the "processed" offset for each topic partition.

It's perfectly possible to have one consumer group per topic – there are different tradeoffs in place.

> What I believe is required from consumer:
> 
> - Autodiscovery of Kafka cluster structure based on Zookeeper - that way there would not be need to restart consumer on each cluster change. it should automatically reconfigure. Now we do that on our own: https://github.com/karafka/karafka/blob/master/lib/karafka/connection/broker_manager.rb but for me it is a really low level feature. The upper layer can be implemented in users code - for example let's say that we shut down all the current Kafkas and spin up new once (one by one it the same cluster) - at some point currently running process won't have Kafkas to listen to. With autodiscovery I could just recreate a consumer and it would fetch new brokers. That would require from me catching a single error and having a failover loop.

I'm actually not planning on supporting any Zookeeper integration, since Kafka 0.9 has removed the need. You'll have to instantiate ruby-kafka with a list of seed brokers. Broker failure is already handled. We could support *all* seed brokers going down after initialization by resetting the seed broker list after doing a cluster metadata discovery, adding any brokers that weren't on the original list.

**Comment by mensfeld** [comment]
> This mirrors my implementation of Producer, which buffers and sends messages for an arbitrary number of topics.

Won't this introduce a offset  committing  issues?

>  Actually committing the offsets would then be a separate logical action, where the consumer would commit the "processed" offset for each topic partition.

It's ok with what we need as long as we have control over the flow.

> Broker failure is already handled
> We could support all seed brokers going down after initialization by resetting the seed broker list after doing a cluster metadata discovery, adding any brokers that weren't on the original list.

And this is enough for me since broker discovery is already in Karafka and it can stay there if you're not planning to be dependent with that driver on Zookeeper at all.

**Comment by dasch** [comment]
> > This mirrors my implementation of Producer, which buffers and sends messages for an arbitrary number of topics.
> 
> Won't this introduce a offset  committing  issues?

I'm not sure I understand?

The idea is to split the commit action into two phases: staging and commit. In the staging phase, the processed offset for each partition is marked as messages are processed, either automatically or manually. The commit phase will send a single request to the broker containing all the offsets. It's just a matter of design – centralizing state makes it easier to do failure recovery, for instance. I've designed ruby-kafka with two API layers, a thin one (Kafka::Broker) that closely mirrors the request/response nature of the protocol, and a fat one (currently just Producer) that provides a more natural Ruby API and manages state, error handling, and retries.

> >  Actually committing the offsets would then be a separate logical action, where the consumer would commit the "processed" offset for each topic partition.
> 
> It's ok with what we need as long as we have control over the flow.

:+1:
 
> > Broker failure is already handled
> > We could support all seed brokers going down after initialization by resetting the seed broker list after doing a cluster metadata discovery, adding any brokers that weren't on the original list.
> 
> And this is enough for me since broker discovery is already in Karafka and it can stay there if you're not planning to be dependent with that driver on Zookeeper at all.

:+1: :+1:

**Comment by michaeldauria** [comment]
I personally would like to use a loop so that i could:
- fetch a bunch of messages from a particular partition
- process them one by one
- once all the messages i have fetched have been processed, commit the offset
- move to another partition and repeat

This would allow a single consumer to process messages from more than one partition and only commit offsets once a batch was processed, which is more performant than sending the offsets in one by one.

I would also love to see exceptions thrown for things like `NotLeaderForPartition` and friends so that we could stop processing messages and rebuild the consumer group.

With that said, would you want to support automatically rebuilding the cluster or should that fall onto the user of the library?

**Comment by dasch** [comment]
@michaeldauria I'm still fleshing out the consumer API, so this is valuable feedback. I believe most of what you're proposing has already been implemented in the batch API: http://www.rubydoc.info/github/zendesk/ruby-kafka/master/Kafka%2FConsumer%3Aeach_batch

For example:

```ruby
consumer.each_batch do |batch|
  puts "Processing #{batch.partition}"

  batch.messages.each do |message|
    process_message(message)
  end

  puts "Finished processing #{batch.partition}
end
```

`#each_batch` will fetch batches of messages from the partitions assigned to the consumer, yielding each to the consumer block. After the block completes successfully, the offset of the last message in the batch is committed before the next batch is yielded.

Regarding exceptions: currently, the consumer group should self-heal, although I'm still in the process of tuning everything.

Does this answer your questions? Once I feel more confident in the stability of the API I'll start documenting it.

**Comment by michaeldauria** [comment]
Yes, that sounds great for me. If the self healing is true that is obviously a huge bonus for me, currently with poseidon_cluster I have issues when processing the messages from Kafka is slow. This can cause partitions to not be subscribed to, which forces me to restart the consumers, or in some cases just stop one, to get things processing again.

I also have seen issues where all of my consumers need to be restarted due to a `NotLeaderForPartition`, which seems to happen for me about once a month.

If using `each_batch` can accomplish processing of messages across many consumers for a single topic, why do you need to add a new API, or am I missing something?

**Comment by dasch** [comment]
@michaeldauria it's just that the API, both `each_message` and `each_batch`, has not been quite finalized yet, as in I'm still reserving the right to change it. We're still in the process of upgrading to Kafka 0.9, so I can't test it out in production myself, which I want to do before marking it as stable. But I encourage you to use the batch API and provide feedback.

As for consumers being kicked out of the group if they're too slow: in ruby-kafka, they'll rejoin, but if you have a slow consumer you'll want to configure the session timeout to be greater than your expected batch process time.
