### ISSUE TITLE
Don't mask everything as a ProcessingError

### ISSUE THREAD

**Issue by pbrisbin** [zendesk/ruby-kafka#356]
https://github.com/zendesk/ruby-kafka/blob/51dbfe2261817205415fc2ca8b9336dd115c73df/lib/kafka/consumer.rb#L202

This causes us a few headaches:

- Every exception in Bugsnag has this class, so we can't Ignore, Fix, or Snooze independently
- Our own outer `rescue` strategy (to tick metrics, silence expected issues, etc) can't just `rescue` what we want, it has to rescue this and check `#cause`

Is there a reason you're not re-`raise`ing the original exception?

**Comment by dasch** [comment]
There are several reasons:

1) I don't want to use a catch-all `rescue` in the async producer; it's important to be able to identify errors raised in the user code.
2) I need to be able to "decorate" the exceptions with the topic/partition/offset information in order to provide actionable information to operators.

Is it difficult to check `#cause`? You could simply do this:

```ruby
case exception.cause
  when SomeError then "some error"
  when RuntimeError then "omg"
end
```

We extract the original exception when reporting exceptions to our tracking system and add the decorated info, e.g.

```ruby
ErrorTracker.track(exception.cause, topic: exception.topic, partition: exception.partition, offset: exception.offset)
```

This works fine for us.

**Comment by pbrisbin** [comment]
Thank you for the info, we will figure out one of the work-around options.
