### ISSUE TITLE
Confusion on thread safety

### ISSUE THREAD

**Issue by marcreynolds** [zendesk/ruby-kafka#360]
This is an issue purely about documentation.

In the `Thread Safety` section, it says the following:

> You typically don't want to share a Kafka client between threads, since the network communication is not synchronized.

That is then followed by:

> You should also avoid sharing a synchronous producer between threads, as the internal buffers are not thread safe. However, the asynchronous producer should be safe to use in a multi-threaded environment.

At first, this seemed like a bit of a contradiction, given that asynchronous producers reference a Kafka client.  Does this mean that asynchronous producers _can_ be shared across threads, but Kafka clients _cannot_ be shared across threads, which could then create asynchronous producers using the shared Kafka client?

**Comment by dasch** [comment]
I see that it's a bit confusing – I should clear up the README. Basically, when you create a producer it gets its own, separate pool of connections to the Kafka cluster and is therefore operating independently of the main client object. Furthermore, the async producer can be shared between threads because that pool is only accessed in a single background thread – the foreground threads send messages unidirectionally over a thread-safe queue, giving the background thread exclusive access to the non-thread-safe parts.

**Comment by dasch** [comment]
Updated the README.

**Comment by marcreynolds** [comment]
@dasch Thanks!
