### ISSUE TITLE
Joining a group does not update offsets

### ISSUE THREAD

**Issue by michaelsauter** [zendesk/ruby-kafka#474]
* Version of Ruby: 2.4.1
* Version of Kafka: 10.1
* Version of ruby-kafka: 0.4.1

Given the following:

* 1 broker with topic "test" which has 3 partitions
* 3 consumer processes (one consumer group), with the following pseudo-code:
```
consumer.subscribe(...)
some_offsets_hash.each { |k, v| consumer.seek("test", k, v)
consumer.each_message { |m| ... }
```

When all processes are started at the same time, sometimes all partitions are assigned to one process only, and it starts fetching messages before a rebalance is triggered and commits the offsets. If that happens, then after the rebalance (now every process is assigned one partition), the 2 processes which did not process any messages so far start from the position that `seek` set, not from the offsets that were committed.

This looks like a bug to me - I would have expected that joining a group results in offsets being fetched from the broker again.

**Comment by dasch** [comment]
It looks like a bug to me, as well. Unfortunately, we cannot commit those offsets until we've joined the group – but I guess the right course of action would be to immediately commit those offsets once we have.

**Comment by mensfeld** [comment]
@dasch can't we refetch the offset upon joining?

**Comment by dasch** [comment]
Not if they haven't been committed yet :)

**Comment by michaelsauter** [comment]
@dasch I'm not sure I'm following. One process (let's call it A), is fetching messages and commits offsets, while the other two (B and C) do nothing. Then a rebalance is triggered. B and C are assigned one partition and start from the original offsets, not from the ones that A committed. I thought we could simply fetch offsets from the broker whenever a consumer joins a goup?

**Comment by dasch** [comment]
Re-reading the original comment, this doesn't actually sound like a bug to me – `seek` is _supposed_ to overwrite the offsets that have been committed. Seeking just once is a bit tricky, since the overwriting of offsets must happen while the consumer is part of the group.

Probably a better way to seek a group is to shut it down, then launch a script that joins the group, seeks the partitions to the desired offsets, then quits, after which you can restart the group and have it resume from those offsets.

This would probably require changing `seek` or adding a variation of it that actually joins the group. It's not simple, though.
