### ISSUE TITLE
Implement speedups using librdkafka

### ISSUE THREAD

**Issue by thedrow** [zendesk/ruby-kafka#49]
[librdkafka](https://github.com/edenhill/librdkafka) is a C client for kafka.
[PyKafka](https://github.com/Parsely/pykafka) uses it in order to speed up consumption and publishing of events.
It be useful to have that functionality in Ruby as well.

**Comment by dasch** [comment]
[Hermann](https://github.com/reiseburo/hermann) is a Ruby library built on top of librdkafka. Using the C library is not a priority for ruby-kafka, because:

1. Typically it's the network that's the bottleneck;
2. the complexity introduced by using a C extension is rather significant;
3. the API is very far from what I'd like to have in ruby-kafka; and
4. it would be much more difficult to implement important features such as fine grained instrumentation if most of the code was in a C library.
