### ISSUE TITLE
Q: One partition, many consumers

### ISSUE THREAD

**Issue by fxn** [zendesk/ruby-kafka#542]
Asking here as per the README instructions.

I need to consume a topic that has one partition and I am trying to understand two scenarios in which the same consumer group could have two consumers:

* Setting up two machines for high-availability.
* Coexistence of listeners in deployments of code updates without downtime.

I know that one consumer group normally has less consumers than partitions (or equal), but given that partition assignment is done by the broker, I don't quite see a technical reason why the situation above couldn't work.

Indeed, in my tests `ruby-kafka` seems to handle this just fine. The active consumer processes messages, and the additional ones (I launched two of them) are there doing nothing, though they keep checking something every second:

```
D, [2018-02-20T17:44:23.083772 #7906] DEBUG -- : Waiting for response 28 from ubuntu:9092
D, [2018-02-20T17:44:23.084096 #7906] DEBUG -- : Received response 28 from ubuntu:9092
I, [2018-02-20T17:44:23.084179 #7906]  INFO -- : There are no partitions to fetch from, sleeping for 1s
I, [2018-02-20T17:44:24.084763 #7906]  INFO -- : There are no partitions to fetch from, sleeping for 1s
I, [2018-02-20T17:44:25.085194 #7906]  INFO -- : There are no partitions to fetch from, sleeping for 1s
I, [2018-02-20T17:44:26.087011 #7906]  INFO -- : There are no partitions to fetch from, sleeping for 1s
...
```

The command-line utility distributed with Kafka (`bin/kafka-console-consumer.sh`) seems to sit there just idle, though `ruby-kafka` seems also idle with default logger, so perhaps it only _appears_ to be idle.

Do you know what is the behavior of the broker when a consumer is connected but cannot assign a partition to it because there are as many consumers as partitions for its consumer group? I have not been able to find documentation about it in the Kafka official docs.

What is `ruby-kafka` trying there every second? Do consumers need to check for rebalancing actively instead of being idle and be notified by Kafka?

Could it be the case that the Scala client is also retrying as `ruby-kafka` does? I mean, maybe that's the only possible behavior?

Do you see anything that's fundamentally/technically wrong with this approach aside from nagging Kafka every 1s for days?

**Comment by nguyenquangminh0711** [comment]
Hi @fxn,

The behaviors of your consumers are totally normal and intentional. By the design, each partition of a topic is exclusively consumed by a consumer; and a partition could not be shared between many partitions. This design ensures the consuming order of the same partition. The consumer group must respect this principle when they decide the group assignment. Therefore, when the number of consumers is greater than the partitions, some of them just idle and do nothing. This behavior is not written in the official document, this is the only possible correct behaviors for the clients to implement. From the environments that I'm working on, as well as from some of my friends', the best practice to scale up is to increase the number of partitions. 

About your second question, in the consuming process, Kafka takes a really passive role, while the consumers take an active role. It means that the clients keep polling from Kafka; there aren't' any mechanism for Kafka to actively notify consumers. Subsequently, in your example, when the consumer tries to fetch the message batch from Kafka, it receives an error message about the assignment situation and just simply for a number of seconds and tries again. 

I don't know about the Scala client, so I couldn't answer your question about this. But in my knowledge, the Java relative languages are the first class in Kafka world. So, it actually many steps ahead of `ruby-kafka` (feature-wised).

One more thing, since the version 0.9, Kafka follows the [client-side assignment design](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal), which means that the partition assignment logic belongs to the client side. The broker does not involve in this process. `ruby-kafka` only supports round-robin assignment. You can get the assignment detail in `lib/kafka/round_robin_assignment_strategy.rb`. 

Hope that would help 😄

**Comment by fxn** [comment]
Awesome reply!

Let me try to understand the impact of extra consumers in the client-side. Let's say we have one partition, one active consumer, and you launch three extra machines, each one with one consumer for that same consumer group.

Are those three extra consumers able to join the consumer group and then `poll` but receive no messages? If yes, is that `poll` call just bloking for `poll.ms` milliseconds? Or do they get an error from the broker?

I see there is a `max.poll.interval.ms` that defaults to 5 minutes. If the consumers are actually able to join the group and they keep polling, I guess this won't be reached (due to the 1s retries) and therefore they won't be kicked out of the group. Squares?

**Comment by dasch** [comment]
> [snip] It means that the clients keep polling from Kafka; there aren't' any mechanism for Kafka to actively notify consumers. Subsequently, in your example, when the consumer tries to fetch the message batch from Kafka, it receives an error message about the assignment situation and just simply for a number of seconds and tries again.

Actually, fetching is not part of the consumer group API. Rather, the periodic heartbeat request that each consumer is required to send back to the group's controller broker is used to notify the consumers that a new "generation" of the group has been created, and that they need to rejoin, which will trigger another round of partition assignment. It's correct that this is done by the consumers themselves – one is selected as group leader by the broker and sends back the assignments.

@fxn in your scenario, the three extra consumers will simply sleep and periodically send in a heartbeat request (see `heartbeat_interval` for a way to configure the frequency). If the active consumer dies, it will either tell the broker with a leave request, if there's no time for that, the broker will notice once the heartbeat isn't sent. That would trigger a new group generation, and the response to the other consumers' heartbeats would indicate as such, causing them to rejoin, one to be selected as leader, and the partition to be assigned to one of the remaining three consumers.

**Comment by fxn** [comment]
@dash and the heartbeats of the idle consumers would trigger rebalances causing an overhead? Guess not, but let me confirm :).

**Comment by dasch** [comment]
There is only a rebalance, i.e. a new group generation (which leads to new assignments), if a group member comes or goes. So if one of the idle consumers fails to send in a heartbeat you'd get a rebalance. But that shouldn't happen – they send in heartbeats even when idle.

**Comment by dasch** [comment]
You definitely want to avoid having consumer come and go often – stability is key to performance.

**Comment by fxn** [comment]
@dasch don't know technically if heartbeats count for `max.poll.interval.ms`. Would the idle consumers be kicked out after that interval and trigger a rebalance?

**Comment by dasch** [comment]
I _think_ that config is only used in the Java client, and thus not enforced by the brokers.

**Comment by dasch** [comment]
That is, if the Java client library doesn't get a `poll` call within that interval, it assumes that the user of the client is blocked or dead and proactively leaves the group.

**Comment by nguyenquangminh0711** [comment]
It is true that that option is for [Java client](https://github.com/apache/kafka/blob/75df8cc77adc61746b3abd0e48d2c7a343e805f6/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L170) only. The broker doesn't have this config.

**Comment by fxn** [comment]
So the conclusion seems to be that this approach is technically sound. This topic doesn't have enough volume to justify several partitions for scalability purposes. If we don't need them either for the use cases above, then one partition is simpler.

Guys this help has been extraordinary, gotta have a beer if we ever meet in a conference. Thanks very much! ❤️

**Comment by dasch** [comment]
No problem, let me know if you run into any issues 😄
