### ISSUE TITLE
Persistent offline producer cache?

### ISSUE THREAD

**Issue by rgaufman** [zendesk/ruby-kafka#568]
This is more of a question than an issue. If the device is offline for an extended period of time, is there some strategy in ruby-kafka to store the messages locally until the connection is restored and they can be sent to the broker?

What about if the process is killed, is there any way to have a persistent store of these pending messages to be sent when the connection is restored?

**Comment by nguyenquangminh0711** [comment]
@rgaufman ruby-kafka uses an internal buffer to store the messages you pass into producer. There aren't any strategy to persist those messages. When a devise is offline and the process is still alive, ruby-kafka keeps retrying until the connection is back. In that period, if the process is killed, it is unfortunate that all messages will be lost. 

The message persistence could be done, but at a higher level than ruby-kafka. ruby-kafka provides instrumentations and enough interfaces for this task. This is my current solution that I am using, perhaps this could work for you. When the process is shut down, I shutdown the producer, which will disconnects all connections to Kafka, then I persists all messages Redis, using list. When the process starts a again, I read the old data from Redis with pop operator. This works well for me on production when the processes stop gracefully. If you want to support higher level of reliability, you could sync to Redis when a message is pushed into buffer, and remove it when a message is successfully delivered. The downside is that this approach increases the overhead for each message, and you must be careful about message duplication when the producer recovers from a crash. I choose redis because it is suitable for my deployment strategy, you could use any other storages, even a system file.

**Comment by dasch** [comment]
ruby-kafka doesn't offer anything out of the box, but as @nguyenquangminh0711 says, you can built something yourself. For local disk persistence, this could work:

```ruby
require "kafka"
require "json"

class PersistentProducer
  BUFFER_FILE = "kafka-message-buffer"

  def initialize(producer:, buffer: [])
    @producer = producer
    @buffer = buffer
    @file = File.new(BUFFER_FILE, "w")

    # Cheat and reuse the encoder from ruby-kafka.
    @encoder = Kafka::Protocol::Encoder.new(@file)
  end

  def produce(key:, value:, topic:, partition_key:)
    message = { key: key, value: value, topic: topic, partition_key: partition_key }
    @buffer << message
    persist(message)
  end

  def deliver_messages
    @buffer.each do |message|
      @producer.produce(**message)
    end

    @producer.deliver_messages
  end

  def self.restore_from_disk(producer:)
    buffer = []

    File.open(BUFFER_FILE, "r") do |file|
      decoder = Kafka::Protocol::Decoder.new(file)

      until decoder.eof?
        data = decoder.bytes
        message = JSON.parse(data)

        buffer << message
      end
    end

    new(producer: producer, buffer: buffer)
  end

  private

  def persist(message)
    data = JSON.dump(message)

    @encoder.write_bytes(data)

    # Make sure the data is written to disk.
    @file.flush
  end
end
```

**Comment by nguyenquangminh0711** [comment]
I haven't heard from you for a while and I think this problem should be handled outside of ruby-kafka gem. Therefore, I'll close this issue. Please feel free to re-open it in case you have further questions related to this.
