### ISSUE TITLE
Resque and ruby-kafka Async?

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#589]
* Version of Ruby: 2.4.3
* Version of Kafka: 1.0.0
* Version of ruby-kafka: 0.5.4

Shot in the dark, has anyone successfully used the async producer with Resque? What was your initialization logic? We're trying to find a solution that allows Resque jobs to share a connection, but everything we've tried either causes lost messages, or we have to connect to the cluster in every job. Any help appreciated!

**Comment by nguyenquangminh0711** [comment]
Hi @bradurani, I'm using async producer with Sidekiq (25 threads, 1 shared async producer instance) and Puma (3 processes, 25 threads each process, 1 async producer instance per process). Everything works fine for me, there aren't any problems so far. Resque is different, it follows forking approach, which it forks a new process and handle the job in that. The AsyncProducer spawns two threads, 1 timer thread and 1 worker thread and maintains a queue to pass the messages from current thread to those 2 threads.  I feel like the forking behaviors of Resque would effect the behaviors of Async Producer, but not 100% sure about this. Perhaps you could follow this approach to investigate more. I'll try to reproduce your problem to have a clearer answer 💪

**Comment by dasch** [comment]
Yeah, I think a forking Resque configuration is the worst possible way to produce to Kafka. I'd investigate Sidekiq or non-forking Resque.

**Comment by nguyenquangminh0711** [comment]
Hi @bradurani,

I'm not sure whether you still follow this topic or not. I had a look at the problem you are facing. To sum up, I don't think the async producer is the best choice for your use case. 

As I mentioned above, AsyncProducer creates two threads and use a `Queue` object as the communication queue between those threads. When you creates an instance of AsyncProducer in main Resque process (say pid1), the queue object exists in this process. When a job starts, Resque forks the current process (say pid2) and it creates a clone of the queue object. Therefore, whenever you do in pid2, all the data pushed to AsyncProducer is stored in cloned queue object in pid2; pid1 doesn't know anything about this. This fails your intention of re-using the connections and publishing logics. 

The message lost situation you meet, IMO, is because the workers threads of AsyncProducer don't finish its jobs in time, before the child process pid2 is killed. Therefore, you must wait for the async producer to finish its job. In addition, there is a really bad situation that if the queue's object in pid1 is *not empty* when the forking process happens, you will end up with message duplication.

From the above points, AsyncProducer is error-prone and doesn't bring any advantages on the table. I think you'll need to create a normal sync producer for each job. That would be the safest solution. If the number of messages to produce in each job is high, I think it is not bad at all. 

Hope this is useful for you 💃

**Comment by bradurani** [comment]
Thanks @nguyenquangminh0711 !

Thanks for the clear explanation! We experimented with this quite a bit and came to the same conclusion you did, though without the same depth of understanding you've given us here. We're currently running about 13m Sidekiq jobs and 750k Resque jobs a day. The solution we came up with is that anytime we want to enqueue something in Kafka from Resque, we create a Sidekiq job from Resque and then enqueue in Kafka from Sidekiq.

Thanks again for experimenting with this!
