### ISSUE TITLE
ActiveSupport < 4.0 not supported?

### ISSUE THREAD

**Issue by SebastianCoetzee** [zendesk/ruby-kafka#621]
I have a Rails app that is running v3.2.22.9 of Rails and v2.3.6 of Ruby and it fails to boot when version 0.6.7 of `ruby-kafka` gem is included in the Gemfile. The following is the stack trace:

```
LoadError: cannot load such file -- active_support/subscriber
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.9/lib/active_support/dependencies.rb:251:in `block in require'
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22.9/lib/active_support/dependencies.rb:251:in `require'
/home/travis/build/yyy/yyy/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.7/lib/kafka/datadog.rb:10:in `<top (required)>'
```

The reason for this is because `active_support/subscriber` is not available in <4.0 of ActiveSupport. Is this dependency restriction by design or may I submit a PR to include the functionality of this class within the `ruby-kafka` gem, thereby allowing the gem to be compatible with ActiveSupport <4.0?

**Comment by nguyenquangminh0711** [comment]
The datalog plugin uses active support subscriber internally to perform its functionalities, so I'm afraid we can't change this dependency, at least in near future. By default, ruby-kafka doesn't load datadog and `active_support/subscriber`, so the normal users won't have any problem with this. 

Since we can't do anything about this, I think I'll close this issue, until we come up with a better solution.
