### ISSUE TITLE
Seeking to specific offsets duplicate the fetched message

### ISSUE THREAD

**Issue by pascalmail** [zendesk/ruby-kafka#669]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.1
* Version of Kafka: 1.1.0
* Version of ruby-kafka: 0.7.3 and master(c739647)

The bug(?) is not present in version 0.7.2

###### Steps to reproduce

```ruby
require 'kafka'

brokers = ['127.0.0.1:9092']
topic = 'seek_test'
group_id = 'seeker'

client = Kafka.new(brokers)
client.delete_topic(topic) rescue nil

producer = client.producer
(1..4).each do |i|
  producer.produce("msg#{i}", topic: topic)
  producer.deliver_messages
end

consumer = client.consumer(group_id: group_id)
consumer.subscribe(topic)

topic_offsets = client.last_offsets_for(topic)[topic]
topic_offsets.each do |partition, last_offset|
    # seek so it can consume from last 2 message
    consumer.seek(topic, partition, last_offset-2)
end

consumer.each_message do |msg|
    puts msg.value
end

```

###### Expected outcome
```
msg3
msg4
```

###### Actual outcome
```
msg3
msg4
msg3
msg4
```

It looks like ruby-kafka fetch the message from the offsets twice.

**Comment by nguyenquangminh0711** [comment]
Hi @pascalmail, thanks for your report. This is an interesting bug. In summary, the root cause of the bug comes from the race condition between the consumer and its Fetcher thread. The fetcher starts when the consumer enters consumer loop (via `each_message` or `each_batch` method). Right after that, the consumer performs group joining. If the group join process takes long enough, the consumer calls fetcher to clean up and restart **after** the first batch arrives. That causes the duplicaiton. 

The fix is not hard, we need to ensure the fetcher starts after the consumer joins the group. In fact, it is speculative for the fetcher to fetch the batches before that.

The reason why version 0.7.2 doesn't have this error because the fetcher thread starts to accept the commands from the consumer after it is created. So, when there is no command and it doesn't start yet, it goes to sleep for 100ms. Then, the join group happens during this time frame and is safe from the issue. If the join group process takes more than 100ms, the issue will appear in releases before version 0.7.2. From version 0.7.3, it only accepts the commands after it starts, so, the sleeping doesn't happen, and expose the bug permernantly. 

I'll implement a fix and add this case into the test suite. Perhaps it would be available in next some days.

cc @dasch

**Comment by swzensar8** [comment]
Hello Team, I am also facing message duplication issue due to this its creating duplicate entries in database within fraction of second, Please tell me in which version of ruby-kafka has fixed this issue.

Eg: In following example we have uniqueness validation for pid at active record level and index level but still not avoiding duplication. I think KAFKA is doing duplication while subscribing  message with in fraction of time.

  id: 1232,
  created_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  updated_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  pid: 112233>,
 #<abc:0x0000000008fd4208
  id: 13083,
  created_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  updated_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  pid: 112233>,
 #<abc:0x0000000008fd40a0
  id: 13085,
  created_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  updated_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  pid: 112233>,
 #<abc:0x0000000008fc7f58
  id: 13087,
  created_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  updated_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  pid: 112233>,
 #<abc:0x0000000008fc7df0
  id: 13089,
  created_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  updated_at: Mon, 07 Jan 2019 17:13:31 CST -06:00,
  pid: 112233>,
