### ISSUE TITLE
0.7.6: logging interface more restrictive

### ISSUE THREAD

**Issue by amacleay** [zendesk/ruby-kafka#717]
If this is a bug report, please fill out the following:

* Version of Ruby: ruby 2.3.3p222
* Version of Kafka: n/a
* Version of ruby-kafka: 0.7.6

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'ruby-kafka', '0.7.6'
  gem 'logging', '2.2.2'
end

Kafka.new(['localhost:9092'], logger: Logging.logger(STDOUT))

puts 'Success'
```

###### Expected outcome

With ruby-kafka version 0.7.5, this little example succeeds and we see `Success` and a clean exit

###### Actual outcome

```
$ ruby test.rb
/home/amacleay/.rvm/gems/ruby-2.3.3@cp/gems/ruby-kafka-0.7.6/lib/kafka/tagged_logger.rb:57:in `new': undefined method `formatter=' for #<Logging::Logger:0x0055c880989628> (NoMethodError)
Did you mean?  formatter
        from /home/amacleay/.rvm/gems/ruby-2.3.3@cp/gems/ruby-kafka-0.7.6/lib/kafka/client.rb:75:in `initialize'
        from /home/amacleay/.rvm/gems/ruby-2.3.3@cp/gems/ruby-kafka-0.7.6/lib/kafka.rb:368:in `new'
        from /home/amacleay/.rvm/gems/ruby-2.3.3@cp/gems/ruby-kafka-0.7.6/lib/kafka.rb:368:in `new'
        from test.rb:9:in `<main>'
```
I don't know if it was intentional for 0.7.6 to require a different logger interface or not, but since it's a patch version I surmise it's not intentional.

Thanks for taking a look!

**Comment by mensfeld** [comment]
Just to be clear, the `#formatter=` is part of the standard Ruby logger API: https://ruby-doc.org/stdlib-2.1.4/libdoc/logger/rdoc/Logger.html

**Comment by amacleay** [comment]
(To be perfectly honest, I have no idea why we're using Logging rather than Logger and this may spur us on to switching - thank you!)

**Comment by dasch** [comment]
@amacleay have you resolved this?

**Comment by MiralDesai** [comment]
I've rolled back to using 0.75 in the meantime. Works with that.

**Comment by dorner** [comment]
Yeah I'm not sure why that Logging gem deliberately does not implement the full Logger interface. 🤔

**Comment by amacleay** [comment]
@dasch We've not. For now we've pinned ruby-kafka, simply because we haven't prioritized switching off Logging yet.

**Comment by capripot** [comment]
Yeah I experienced the same issue, tried to debug but Im running out of time.
Given that I use Phobos, with a configure file following what is described in the project.

`phobos.yml`:
```yml
logger:
  # Optional log file, set to false or remove to disable it
  file: false
  level: warn
  stdout_json: true
  # Comment the block to disable ruby-kafka logs
  ruby_kafka:
    level: warn
```

I get the following error: `TypeError: no implicit conversion of Logging::Logger into String`. It might be due to to that condition: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/tagged_logger.rb#L60
Doesn't look like `Logging::Logger` is a `Logger`, so it goes to `::Logger.new(logger_or_stream)` which fails since `logger_or_stream` is not a URI string, but a 
`Logging::Logger`, hence the `no implicit conversion of Logging::Logger into String`.

I hope that can help resolving the issue.

**Comment by dorner** [comment]
Opened #762 to fix this.
